/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iflytek_dicom_DicomParse */

#ifndef _Included_com_iflytek_dicom_DicomParse
#define _Included_com_iflytek_dicom_DicomParse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomUninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomUninit
  (JNIEnv *, jclass);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomCreateInst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomCreateInst
  (JNIEnv *, jobject);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomDestroyInst
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomDestroyInst
  (JNIEnv *, jobject);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomReset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomReset
  (JNIEnv *, jobject);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomLoadFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomLoadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomLoadBuf
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomLoadBuf
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomParse
 * Signature: (Lcom/iflytek/dicom/DicomInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomParse
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_iflytek_dicom_DicomParse
 * Method:    JniIdicomGetData
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_dicom_DicomParse_JniIdicomGetData
  (JNIEnv *, jobject, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
